[package]
name = "nwjs-sys"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/aspectron/cargo-emanate"
keywords = ["cargo", "subcommand", "installation", "package","nwjs"]
categories = ["command-line-utilities", "development-tools::cargo-plugins", "development-tools::build-utils"]
exclude = ["/.*", "/test"]
description = """
NWJS API
"""

[dependencies]
wasm-bindgen = "0.2.79"
workflow-wasm = {path="../workflow-wasm"}
workflow-log = "*"
js-sys = "0.3.56"
thiserror = "1.0"

[dependencies.web-sys]
version = "0.3.60"
features = [
    'console',
    'Document',
    'Window',
    'HtmlElement'
]
